feat: SpacerコンポーネントのStorybookを作成した
ltoppyl/mahjong-score-manage pull request #89
Opened 2023-05-06 16:56 UTC by ksr03

## 🔨 変更内容

- HSpacerとVSpacerのストーリーを作成した

## 📸 スクリーンショット

## 📢 この PR に含まないこと

- xxx

## 💡 レビューの観点

### PR 作成者のチェック項目

- [ ] セルフレビュー
- [ ] CI/CD がすべて pass している
- [ ] Reviewer の指定

### Reviewer のチェック項目

- [ ] コードレビュー

## ✅ 解決するイシュー

- close #0

## 🤝 関連するイシュー

- #0

2023-05-06 17:03 UTC, ksr03 commented
ストーリーのpropsを指定した時に、HSpacerの見た目の変化が殆ど無いので分かりづらい

2023-05-07 11:46 UTC, ltoppyl commented on frontend/components/atoms/Spacer/HSpacer/index.stories.tsx
> +};
![imo](https://img.shields.io/badge/review-imo-yellow.svg)
こんな感じにすると、size の引数の違いによる描画の差分を確認できると思いますー
[components/organisms/ScoreInputField/index.stories.tsx](https://github.com/ltoppyl/mahjong-score-manage/blob/develop/frontend/components/organisms/ScoreInputField/index.stories.tsx) とか参考になるかもです
```ts
export const Default: StoryObj = (args) => {
  return (
    <>
      <HStack>
        <Box w={##} h={##} bg="tomato" />
        <HSpacer {...args} />
        <Box w={##} h={##} bg="tomato" />
      </HStack>
    </>
  );
};

Default.args = {
  size: 10,
};

```

2023-05-07 11:46 UTC, ltoppyl commented on frontend/components/atoms/Spacer/HSpacer/index.stories.tsx
> +  title: "atoms/HSpacer",
![must](https://img.shields.io/badge/review-must-red.svg)
```suggestion
  title: "atoms/Spacer/HSpacer",
```

2023-05-07 11:46 UTC, ltoppyl commented on frontend/components/atoms/Spacer/HSpacer/index.stories.tsx
Discord での自分の言い方が微妙でしたが、フォルダは以下のどちらかが好みです
パターン1
<pre>
Spacer
├── index.tsx
├── VSpacer.stories.tsx  
└── HSpacer.stories.tsx
</pre>

パターン2
<pre>
Spacer
├── HSpacer
│    ├── index.tsx
│    └── index.stories.tsx
└──  VSpacer
      ├── index.tsx
      └── index.stories.tsx
</pre>

2023-05-08 00:44 UTC, ltoppyl requested changes

2023-05-08 00:44 UTC, ltoppyl commented on frontend/components/atoms/Spacer/HSpacer.stories.tsx
![must](https://img.shields.io/badge/review-must-red.svg)
deploy が import order 周りで落ちているので、`yarn lint --fix` を叩いてみてくださいー

2023-05-08 00:45 UTC, ltoppyl commented
その他は良さそうです！

2023-05-08 04:08 UTC, ksr03 commented
どこでdeployが失敗してるのかってどうやったら分かりますか？

2023-05-08 06:20 UTC, ltoppyl commented
> どこでdeployが失敗してるのかってどうやったら分かりますか？

![image](https://user-images.githubusercontent.com/68209431/236748610-4b3c3771-8372-4ecd-9d39-05c997e2cc0d.png)

「✗」ボタンを押したら出てくる Popover の「Detail」のとこから見れるんですが、無料プランだと、ぼくしか見れなかったはず… (つらい)

ちなみに今回怒られているポイントは⇩⇩
![image](https://user-images.githubusercontent.com/68209431/236748575-4a0a3942-f52a-4dcf-b92a-0fc29fdd9d7a.png)

2023-05-08 06:31 UTC, ltoppyl commented
今回の警告は ESLint ではなく、TypeScript のコンパイラ？の型チェックに怒られているから、`yarn lint` では検知できず、こういうのは `yarn tsc --noEmit` というコマンドで検知できるらしい (初めて知った)
ローカルで叩いてみたら⇩みたいな感じになりました
![image](https://user-images.githubusercontent.com/68209431/236750821-8eac0446-c5a3-4265-8eca-48c1164e84af.png)

2023-05-08 06:34 UTC, ltoppyl commented
神代さんが現時点でできるアクションとしては、push する前に
- `yarn lint`
- `yarn tsc --noEmit`
を実行して、どちらも落ちていないことを確認するっていうのは無駄にデプロイが落ちなくてよいかもしれないですねー

こういうのは本当は CI とかで検知したくて、そもそも `yarn lint` とかが落ちているとき push できないみたいな設定を追加しても良いかも！？(ちょっとめんどくさい)

2023-05-08 11:43 UTC, ltoppyl commented on frontend/components/atoms/Spacer/HSpacer.stories.tsx
> +export const Default: Story = (args: any) => {
基本的には any 型は使いたくない (TypeScript を使ってる意味が薄くなる) ですが、ここはぼくも適切な型がいまいちわかっていないので、他のとこでも暫定的に any 型を使っています。
しかし、そうすると ESLint の Warning がずっと出てしまうので、一時的にそこは許容するような処理をしていて、後に適切な型を与えるという旨のコメントを残しています
https://github.com/ltoppyl/mahjong-score-manage/blob/d7bab0a220e97a2323765eca16deda9e0d1053fc/frontend/components/organisms/ScoreInputField/index.stories.tsx#L12-L14

2023-05-08 12:45 UTC, ltoppyl approved these changes
<img src="https://images.lgtmgen.org/5e7670bc-b970-4788-a689-0956f403ba8f" width="30%">

2023-05-09 09:29 UTC, merged