feat: 3麻と4麻を切り替えられるようにした
ltoppyl/mahjong-score-manage pull request #96
Opened 2023-05-11 17:27 UTC by ksr03

## 🔨 変更内容

- 3麻と4麻をボタンで選択して切り替えられるようにした

## 📸 スクリーンショット

## 📢 この PR に含まないこと

- xxx

## 💡 レビューの観点

### PR 作成者のチェック項目

- [ ] セルフレビュー
- [ ] CI/CD がすべて pass している
- [ ] Reviewer の指定

### Reviewer のチェック項目

- 3麻でも4麻でも「データの送信に失敗しました」と表示されるが、どこに不具合があるのか分からない。
- コードが冗長な気がする
- stateの状態名や更新関数の命名に自信が無い（そもそもstateを使う必要があるのか分からない）

- [ ] コードレビュー

## ✅ 解決するイシュー

- close #77

## 🤝 関連するイシュー

- #0

2023-05-12 04:05 UTC, ltoppyl commented on frontend/components/templates/RecordInput/index.tsx
> Chakra UIのTabsコンポーネントを使えばもっと簡潔なコードになるかもしれない（但しFigmaと全く同じ見た目にするのは難しそう）

おっしゃる通りで、Tabs を使っても同じようなことはできますが、以前 Tabs を使った時細かい UI の挙動の制御が結構難しく、使い勝手が悪かったので、あまり Tabs は使いたくなかったりしますね
Tabs の中の要素がめっちゃ多かったり少なかったりすると、Tabs の選択のとこがあっちいったりこっちいったりしてしまったような記憶があります

2023-05-12 07:49 UTC, ltoppyl requested changes

2023-05-12 07:49 UTC, ltoppyl commented on frontend/components/templates/RecordInput/index.tsx
## 動作的な話で修正したい部分
### 入力周りのバリデーション
  - ex) 「4麻」で「ルール」「着順」を選択した後に「3麻」を選択 、「スコア」を入力 -> 追加ボタンが活性化する
  - 「4麻」「3麻」の切り替えを行った時は、入力周りはすべて初期化するのが無難！？
    -  初期化まではしなくても良いかもしれないけど、着順で「4」を選択している状態 -> 3麻に変更した時に挙動をどう救うかが肝

### 「追加」ボタンが見切れる
- PC の画面だと「追加」ボタンのところが隠れて、スクロールもできなかった 
  ![image](https://github.com/ltoppyl/mahjong-score-manage/assets/68209431/b4636876-159f-498e-a539-f21820fe75a1)
- スマホだとスクロールできてボタン押せた (もう少し space を調整すればスクロールも不要そう)
  - 総じて、サイズ感が Figma と実際とで乖離があるのがとても気になる (自分の方でちゃんと調査します)

⇩の `gameType` 選択の縦前後の 12 当ててる space を 6 とかにしましょうか (PC でボタンが見えていたらスマホでも見えるはず)
![image](https://github.com/ltoppyl/mahjong-score-manage/assets/68209431/b8886c70-c298-434a-a2ad-e7d0057a56d5)

2023-05-17 10:36 UTC, ltoppyl requested changes

2023-05-17 10:36 UTC, ltoppyl commented on frontend/components/templates/RecordInput/index.tsx
>          onClick={() => setIsFourMahjong(gameType === 4 ? true : false)}
![must](https://img.shields.io/badge/review-must-red.svg)
ここも `isFourGameType` に置き換えれそうです

2023-05-17 14:17 UTC, KRei0 commented
(^^)b

2023-05-18 06:31 UTC, ltoppyl approved these changes
<img src="https://i.pinimg.com/originals/9e/31/ca/9e31caaa18ed23b5b984532bb6644126.gif" width="30%">

2023-05-18 08:17 UTC, merged